Dev
Danil2019IT/ProgrammingKPI pull request #2
Opened 2019-11-09 05:31 UTC by Danil2019IT

@nechaido @bugagashenkj

2019-11-09 09:20 UTC, ivan-tymoshenko requested changes

2019-11-09 09:20 UTC, bugagashenkj commented on lab_work_#6/lab_6.py
> +        x1 = i * h1 - h1 / 2
```suggestion
        x1 = a + i * h1 - h1 / 2
```

2019-11-09 14:39 UTC, Danil2019IT commented
@bugagashenkj

2019-11-10 18:45 UTC, bugagashenkj commented on lab_work_#6/lab_6.py
> +
Unnecessary lines

2019-11-10 18:46 UTC, ivan-tymoshenko approved these changes

2019-11-10 19:03 UTC, Danil2019IT commented
@bugagashenkj

2019-11-13 11:06 UTC, merged